# Generated by Django 5.2.14 on 2026-05-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "what",
                    models.CharField(
                        max_length=200, verbose_name="What (何が起きたか)"
                    ),
                ),
                (
                    "why",
                    models.CharField(
                        max_length=200, verbose_name="Why (なぜそうなったか)"
                    ),
                ),
                (
                    "so_what",
                    models.CharField(
                        max_length=200, verbose_name="So What (だから何が言えるか)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "3行要約",
                "verbose_name_plural": "3行要約",
                "ordering": ["-created_at"],
            },
        ),
    ]
