# Generated by Django 5.2.14 on 2026-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(verbose_name='What(何を)')),
                ('why', models.TextField(verbose_name='Why(なぜ)')),
                ('so_what', models.TextField(verbose_name='So what(だから何)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '3行要約',
                'verbose_name_plural': '3行要約',
                'ordering': ['-created_at'],
            },
        ),
    ]
